package com.redhat.demo.iot.datacenter.monitor
 
import com.redhat.demo.iot.datacenter.monitor.DataSet;

rule "VoltageToLow"
	lock-on-active true
	when
		$t : DataSet( deviceType == "voltage", payload < 2000 )
	then
		$t.setRequired(1);
		$t.setErrorCode(1);
		$t.setErrorMessage("Voltage to low");
		update( $t );
		
end 

rule "TemperatureHigh"
	lock-on-active true
	when
		$t : DataSet( deviceType == "temperature", payload > 27 )
	then
		$t.setRequired(1);
		$t.setErrorCode(2);
		$t.setErrorMessage("Temperature to high");
		System.out.println("Temperature to high");
		update( $t );
		
end 
